version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/APICatalog/APICatalog/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: "scope"
